export const mockMode =
  typeof window !== "undefined" &&
  (new URLSearchParams(window.location.search).has("mock") ||
    import.meta.env?.VITE_MOCK === "1");

const now = Date.now();
const pad2 = (n: number) => String(n).padStart(2, "0");

/** Local wall-clock ISO (no timezone) so the 24h mock times render exactly. */
function mins(m: number): string {
  const d = new Date(now + m * 60000);
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}T${pad2(d.getHours())}:${pad2(d.getMinutes())}:${pad2(d.getSeconds())}`;
}

export const mock = {
  me: {
    login: "shrek",
    displayName: "Shrek",
    image: "https://picsum.photos/seed/shrek/200/200",
    wallet: 1234,
    correctionPoints: 42,
    level: 8.47,
    grade: "Ogre at 42cursus",
    campusId: 12,
    campusName: "Duloc",
    poolLabel: "06/2001",
    customAvatar: null,
    avatarBg: "transparent",
    avatarPosX: 50,
    avatarPosY: 50,
    avatarScale: 100,
  },
  upcoming: {
    tracked: true,
    items: [
      {
        id: 1,
        beginAt: mins(35),
        state: "revealed" as const,
        project: "Swamp Defense",
        slug: "swamp-defense",
      },
      {
        id: 2,
        beginAt: mins(3 * 60),
        state: "booked" as const,
        project: "Ogres Have Layers",
        slug: "ogres-have-layers",
      },
      {
        id: 3,
        beginAt: mins(26 * 60),
        state: "booked" as const,
        project: "Far Far Away Sorting",
        slug: "far-far-away-sorting",
      },
    ],
  },
  profileStats: {
    roulette: { entries: [] },
    evalStats: {
      global: { total: 68, failed: 8, successPercentage: 88.2 },
      byMonth: {
        "2026-10": { total: 1, failed: 1, successPercentage: 0 },
        "2026-09": { total: 10, failed: 0, successPercentage: 100 },
        "2026-08": { total: 3, failed: 2, successPercentage: 33.3 },
        "2026-07": { total: 16, failed: 1, successPercentage: 93.8 },
        "2026-06": { total: 11, failed: 2, successPercentage: 81.8 },
        "2026-05": { total: 19, failed: 2, successPercentage: 89.5 },
        "2026-04": { total: 7, failed: 1, successPercentage: 85.7 },
        "2026-03": { total: 12, failed: 2, successPercentage: 83.3 },
        "2026-02": { total: 18, failed: 3, successPercentage: 83.3 },
        "2026-01": { total: 9, failed: 0, successPercentage: 100 },
        "2025-12": { total: 5, failed: 1, successPercentage: 80 },
        "2025-11": { total: 8, failed: 2, successPercentage: 75 },
      },
    },
  },
  friends: [
    {
      login: "fiona",
      displayName: "Fiona",
      avatar: "https://picsum.photos/seed/fiona/200/200",
      customAvatar: null,
      avatarBg: "transparent",
      avatarPosX: 50,
      avatarPosY: 50,
      avatarScale: 100,
      level: 14.32,
      grade: "Ogre at 42cursus",
      isOnline: true,
      lastSeen: "c3r1p2",
      poolLabel: "06/2001",
      wallet: 2100,
      correctionPoints: 12,
      lastOnlineTimestamp: null,
    },
    {
      login: "donkey",
      displayName: "Donkey",
      avatar: "https://picsum.photos/seed/donkey/200/200",
      customAvatar: "/icons/icon-192.png",
      avatarBg: "#5b21b6",
      avatarPosX: 60,
      avatarPosY: 40,
      avatarScale: 130,
      level: 7.9,
      grade: "Learner",
      isOnline: true,
      lastSeen: "c4r2p1",
      poolLabel: null,
      wallet: 842,
      correctionPoints: 3,
      lastOnlineTimestamp: null,
    },
    {
      login: "puss",
      displayName: "Puss in Boots",
      avatar: "https://picsum.photos/seed/puss/200/200",
      customAvatar: null,
      avatarBg: "transparent",
      avatarPosX: 50,
      avatarPosY: 50,
      avatarScale: 100,
      level: 3.42,
      grade: null,
      isOnline: false,
      lastSeen: null,
      poolLabel: "12/2004",
      wallet: 150,
      correctionPoints: 0,
      lastOnlineTimestamp: now - 2 * 3600 * 1000,
    },
    {
      login: "dragon",
      displayName: "Dragon",
      avatar: "https://picsum.photos/seed/dragon/200/200",
      customAvatar: null,
      avatarBg: "transparent",
      avatarPosX: 50,
      avatarPosY: 50,
      avatarScale: 100,
      level: 21.05,
      grade: "Member",
      isOnline: false,
      lastSeen: null,
      poolLabel: null,
      wallet: 3500,
      correctionPoints: 21,
      lastOnlineTimestamp: now - 86400000,
    },
    {
      login: "farquaad",
      displayName: "Lord Farquaad",
      avatar: "https://picsum.photos/seed/farquaad/200/200",
      customAvatar: null,
      avatarBg: "transparent",
      avatarPosX: 50,
      avatarPosY: 50,
      avatarScale: 100,
      level: 5.67,
      grade: "Member",
      isOnline: true,
      lastSeen: "c1r4p3",
      poolLabel: "06/2001",
      wallet: 5,
      correctionPoints: 1,
      lastOnlineTimestamp: null,
    },
  ],
  blob: {
    settings: {
      FRIENDS_LIST: ["fiona", "donkey", "puss", "dragon", "farquaad"],
      DISCORD_QUIET_ENABLED: false,
      DISCORD_QUIET_START: "22:00",
      DISCORD_QUIET_END: "08:00",
      SHOW_CUSTOM_AVATARS_IN_FRIENDS: true,
    },
    revision: "mock",
    discordId: "123456",
    discordUsername: "shrek",
  },
  sessions: {
    max: 20,
    sessions: [
      {
        id: "1",
        label: "Safari · iOS 27",
        current: true,
        createdAt: now - 3600 * 1000,
      },
      {
        id: "2",
        label: "Firefox 131",
        current: false,
        createdAt: now - 3 * 86400000,
      },
    ],
  },
  events: [
    {
      id: 101,
      name: "🎓 Alumni Fireside Chat #20 with Antoine @Google Cloud and friends",
      beginAt: mins(5 * 24 * 60),
      endAt: mins(5 * 24 * 60 + 60),
      location: "Amphithéâtre",
      url: "https://events.intra.42.fr/events/101",
    },
    {
      id: 102,
      name: "⚙️ 42 Workspace: Docker for beginners",
      beginAt: mins(24 * 60 + 45),
      endAt: mins(24 * 60 + 45 + 120),
      location: "Room 4.2",
      url: "https://events.intra.42.fr/events/102",
    },
    {
      id: 103,
      name: "🛠 Hackathon: Neural link",
      beginAt: mins(3 * 24 * 60),
      endAt: mins(3 * 24 * 60 + 6 * 60),
      location: "The Hive",
      url: "https://events.intra.42.fr/events/103",
    },
    {
      id: 104,
      name: "🍝 Meetup: 42 Pasta Night",
      beginAt: mins(6 * 60),
      endAt: mins(6 * 60 + 120),
      location: null,
      url: "https://events.intra.42.fr/events/104",
    },
    {
      id: 105,
      name: "📚 Exam: Final Exam",
      beginAt: mins(12 * 24 * 60),
      endAt: mins(12 * 24 * 60 + 4 * 60),
      location: "Cluster 1",
      url: "https://events.intra.42.fr/events/105",
    },
  ],
};
